### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by domarmstrong** [mswjs/cookies#16]
Hi, would you mind adding the MIT LICENSE.md file to the repo please (as in https://github.com/mswjs/msw/blob/main/LICENSE.md)?

Thanks very much.

**Comment by kettanaito** [comment]
Hey, @domarmstrong. Thanks for raising this. 

Done in https://github.com/mswjs/cookies/commit/a28d293a4d47a63e86e79573d842816a32bba7d2.
